/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "age": number;
        "first": string;
        "last": string;
        "middle": string;
        "name": string;
    }
    interface MyModal {
        "myTitle": string;
    }
    interface MyTable {
        "myTitle": string;
        "myheaders": string[];
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyModalElement extends Components.MyModal, HTMLStencilElement {
    }
    var HTMLMyModalElement: {
        prototype: HTMLMyModalElement;
        new (): HTMLMyModalElement;
    };
    interface HTMLMyTableElement extends Components.MyTable, HTMLStencilElement {
    }
    var HTMLMyTableElement: {
        prototype: HTMLMyTableElement;
        new (): HTMLMyTableElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-modal": HTMLMyModalElement;
        "my-table": HTMLMyTableElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "age"?: number;
        "first"?: string;
        "last"?: string;
        "middle"?: string;
        "name"?: string;
    }
    interface MyModal {
        "myTitle"?: string;
    }
    interface MyTable {
        "myTitle"?: string;
        "myheaders"?: string[];
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-modal": MyModal;
        "my-table": MyTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-modal": LocalJSX.MyModal & JSXBase.HTMLAttributes<HTMLMyModalElement>;
            "my-table": LocalJSX.MyTable & JSXBase.HTMLAttributes<HTMLMyTableElement>;
        }
    }
}
